### ISSUE TITLE
Current bitcoin market data fails to load

### ISSUE THREAD

**Issue by dannydeezy** [jlopp/us-marshals-bitcoin-auctions#2]
Market data fails to load from CoinMarketCap, due to a CORS error. CoinMarketCap API does not support requests from a client's browser. [See here](https://coinmarketcap.com/api/faq/)

<img width="1364" alt="Screen Shot 2020-03-07 at 2 12 58 PM" src="https://user-images.githubusercontent.com/43550949/76153201-cd506d00-607d-11ea-8b55-036867c5bd7e.png">

I've fixed the issue by replacing CoinMarketCap with CoinGecko, who does support this behavior.

I was unable to push up to a branch in this repo, [so I forked and made a commit here](https://github.com/dannydeezy/us-marshals-bitcoin-auctions/commit/3e95e1890edeb5992aea73b2672df8e31fdb711c)

**Comment by jlopp** [comment]
If you create a different branch in your forked repo with this commit, github ought to give you a button to create a pull request from it

**Comment by dannydeezy** [comment]
Ah [there we go](https://github.com/jlopp/us-marshals-bitcoin-auctions/pull/3), thanks
